language: objective-c
osx_image: "xcode8.2"
xcode_project: v9/v9.xcodeproj # path to your xcodeproj folder
xcode_scheme: v9

script:
    xcodebuild test -project v9/v9.xcodeproj -scheme v9 -destination 'platform=iOS Simulator,name=iPhone 7 Plus,OS=10.2'